prebid/prebid-js-plugin-brightcove

- package.json
- src/BcPrebidVast.js
- src/MarkersHandler.js
- src/PrebidCommunicator.js
- src/VastManager.js
- tests/e2e/auto/VastManagerTest.js
- tests/e2e/testPages/bc_vpaid_vast_mo.css
- tests/e2e/testPages/default-options-playlist.js
- tests/e2e/testPages/prebid-body-ad-server.html
- tests/e2e/testPages/prebid-body-playlist.html
- tests/e2e/testPages/prebid-body.html
- tests/e2e/testPages/prebid-header-ad-server.html
- tests/e2e/testPages/prebid-header.html
- tests/e2e/testPages/prebid-main.html
- tests/e2e/testPages/prebid-studio-config-playlist.html
1. Specify adServerCallback by name
2. Playlisting support
3. Playlisting frequency control
4. VAST Wrapper limit support
5. Bug fixes during testing cycle
> Brightcove Prebid Plugin ver 0.1.1

- package.json
- src/BcPrebidVast.js
- tests/e2e/testPages/prebid-body-ad-server.html
- tests/e2e/testPages/prebid-body-playlist.html
- tests/e2e/testPages/prebid-body.html
- tests/e2e/testPages/prebid-header-ad-server.html
- tests/e2e/testPages/prebid-header.html
> The Open Source Brightcove Prebid Plugin ignores page-level bidderSettings

- src/VastManager.js
iOS - Click is required for ad to be started in every playlisting video
> Fix for VIDLA-3563

- src/VastManager.js
Fix for VIDLA-3860 (iPad,iPhone version 10 - Creative times out on iPad and content video does not play- embedded with options)
> VIDLA-3860 - Creative times out on iPad and content video does not play

- tools/biddersettings.html
This PR includes a simple tool to help developers convert JS bidderSettings to the JSON format required to work in Brightcove Studio.
> VIDLA-3857 Build bidderSettings conversion tool

- src/BcPrebidVast.js
- src/MarkersHandler.js
- tests/e2e/testPages/prebid-main.html
- tests/e2e/testPages/prebid-studio-config.5.28.1.html
Fix for VIDLA-4190 (Prebid plugin does NOT support version 5.28.1 of the Brightcove Player)
> Fix for VIDLA-4190

- src/VastManager.js
VIDLA-4191 (Prebid plugin occasionally exhibits high latency in Brightcove Player)
Also removed old commented code.
> Fix for VIDLA-4191

- package.json
- src/BcPrebidVast.js
- src/VastManager.js
BC Prebid Plugin shows black screen + spinner when sound on prevents autoplay
> VIDLA-4204

- src/VastManager.js
Fix for VIDLA-4209 (Getting Uncaught TypeError: r is not a function" and Content video audible)
> VIDLA-4209

- package.json
- src/BcPrebidVast.js
- src/VastManager.js
Plugin Embedded With Options (Player 5.28.1) - 'Ad' text displaying on top the player when content video playing
> VIDLA-4213

- package.json
- src/BcPrebidVast.js
- tests/e2e/auto/BcPrebidVastTest.js
- tests/e2e/testPages/prebid-body-display.html
- tests/e2e/testPages/prebid-main.html
Investigate solution to prevent contention between prebid for display and prebid for video in same document.
To solve this problem plugin will create friendly iframe and load into it prebid.js.
> VIDLA-4302

- package.json
- src/AdListManager.js
- src/BcPrebidVast.js
- src/MarkersHandler.js
- src/VastManager.js
- tests/e2e/auto/AdListManagerTest.js
- tests/e2e/auto/BcPrebidVastTest.js
- tests/e2e/auto/PrebidCommunicatorTest.js
- tests/e2e/auto/VastManagerTest.js
- tests/e2e/testPages/default-options-multi.js
- tests/e2e/testPages/prebid-body-multi-playlist.html
- tests/e2e/testPages/prebid-body-multi.html
- tests/e2e/testPages/prebid-main.html
Implement support for multiple prebid spots in a single content video
> VIDLA-4210

- package.json
- src/BcPrebidVast.js
Investigate solution to prevent contention between prebid for display and prebid for video in same document.
Prevents again listening unfamiliar post messages.
> More fix for VIDLA-4302

- package.json
- src/BcPrebidVast.js
- tests/e2e/auto/BcPrebidVastTest.js
- tests/e2e/testPages/prebid-body-display.html
- tests/e2e/testPages/prebid-main.html
Brightcove Prebid Plugin Version 0.2.8
> VIDLA-0.2.6+

- src/BcPrebidVast.js
- tests/e2e/auto/AdListManagerTest.js
- tests/e2e/testPages/prebid-body-display.html
- tests/e2e/testPages/prebid-main.html
Apply changes from 0.2.8 to 0.3
> VIDLA-4334

- src/AdListManager.js
- src/VastRenderer.js
iOS 10, iPhone - Two clicks are needed for the ad to start playing
> VIDLA-4310

- src/AdListManager.js
- src/BcPrebidVast.js
- src/VastManager.js
Android - After launching the initial test page, pre roll ad plays after pause and un-pause the content video
> VIDLA-4227

- package.json
- src/BcPrebidVast.js
- tests/e2e/testPages/prebid-embed-display.html
- tests/e2e/testPages/prebid-embed-multi-display.html
- tests/e2e/testPages/prebid-main.html
Create two new test pages with prebid for display and embedded player.
Also I fix issue to play multi ads in player with plugin embedded in studio.
> VIDLA-4339

- src/AdListManager.js
- src/BcPrebidVast.js
- src/VastManager.js
- tests/e2e/testPages/default-options-multi.js
- tests/e2e/testPages/default-options-playlist.js
- tests/e2e/testPages/default-options.js
make the timeout for loading prebid.js in iframe configurable
> VIDLA-4309

- src/AdListManager.js
Fix for VIDLA-3895 (iOS version 10 iPad- Playlist pages - Two clicks are required to start preroll)
> VIDLA-3895

- src/MarkersHandler.js
Fix for VIDLA-4368 (Getting the selected vast url from PrebidCommunicator, post roll ad does not playing on iOS devices)
> VIDLA-4368

- src/AdListManager.js
- src/MarkersHandler.js
More fix for VIDLA-4368 (iOS - Getting the selected vast url from PrebidCommunicator, post roll ad does not playing on iOS devices)
> VIDLA-4368-2

- gulpfile.js
BC Prebid Plugin breaks Brightcove Studio Preview Player
> Fix for VIDLA-4382

- gulpfile.js
- package.json
- src/BcPrebidLoader.js
- src/BcPrebidVast.js
- tests/e2e/auto/AdListManagerTest.js
- tests/e2e/auto/BcPrebidLoaderTest.js
- tests/e2e/auto/BcPrebidVastTest.js
- tests/e2e/auto/PrebidCommunicatorTest.js
- tests/e2e/auto/VastManagerTest.js
- tests/e2e/auto/VastRendererTest.js
- webpack.conf.plugin.js
> VIDLA-4389

- src/AdListManager.js
Fix for VIDLA-4374 (Playlist page Safari browser- Midroll marker appears twice).
Also fixed logic for postroll in playlist mode.
> VIDLA-4374

- src/AdListManager.js
During testing multi ads in playlist mode I found the plugin in some cases works incorrectly:
1. player not plays next playlist video after ad(s) played
2. plugin stopped to receive playlist events
3. playlist works not correctly if some ad(s) failed
4. playlist works incorrectly after postroll
The changes in this branch fix those issues.
> Enhancement for support multiple ads in playlist mode.

- src/BcPrebidLoader.js
- src/BcPrebidVast.js
- src/PrebidCommunicator.js
- src/PrebidGlobal.js
This merge adds support for multiple Brightcove players with an embedded Prebid Plugin on the same html page (when players are NOT using iframe embeds).
> VIDLA-4391 - Support for Multiple Players with Embedded Prebid Plugin on a Page

- src/AdListManager.js
- src/BcPrebidLoader.js
- src/BcPrebidVast.js
Fix for VIDLA-4467 (Prebid in Header using AdServer throws an error)
> VIDLA-4467

- tests/e2e/testPages/prebid-body-multi-players.html
More implementation for VIDLA-4465 (create test page for non-embedded plugin with two players in the body)
> VIDLA 2 players in html body

- gulpfile.js
- package.json
- src/AdListManager.js
- src/BcPrebidLoader.js
- src/BcPrebidVast.js
Fix for VIDLA-4484 (Android Chrome - embedded page with 2 players- bottom player's content video is seen for a while before Ad starts play).
Fix for VIDLA-4479 (multiplayer - A flash of the first frame is seen before ad plays)
> VIDLA 4479, 4484

- src/BcPrebidLoader.js
- src/VastManager.js
Fix for VIDLA-4490 (Multiads, Embedded multiads page do not load ads, show an error in Console logs)
> VIDLA 4490

- tests/e2e/testPages/prebid-embed-multi-players-iframes.5.28.1.html
- tests/e2e/testPages/prebid-embed-multi-players-iframes.html
- tests/e2e/testPages/prebid-main.html
Added iframe embed code test pages
> VIDLA-4491

- src/BcPrebidVast.js
Fix for VIDLA-4506 (Prebid in Header using AdServer plays an ad but throws an Uncaught Type Error)
> VIDLA-4506

- package.json
- src/BcPrebidLoader.js
Fix for VIDLA-4476 (Stop Ad button does not work on some of the test pages)
> VIDLA-4476

- package.json
- src/BcPrebidVast.js
- src/PrebidCommunicator.js
Fix for VIDLA-4552 (Notify url event_type =1 does not fire when DFP is not used)
> VIDLA-4552

- package.json
- src/BcPrebidVast.js
Fix for VIDLA-4563 (PC Edge browser - Single, Multiplayers in iFrame embed code requires incredibly BIG ad start timeout of 25 seconds for the ad to play)
> VIDLA-4563

- package.json
- src/BcPrebidVast.js
More fix for VIDLA-4563 (PC Edge browser - Single, Multiplayers in iFrame embed code requires incredibly BIG ad start timeout of 25 seconds for the ad to play)
> VIDLA-4563-2

- package.json
- src/BcPrebidVast.js
- src/Logging.js
VIDLA-4615 (Prebid Plugin Console Logs should include player ID for Prebid Plugin)
> VIDLA-4615

- src/BcPrebidLoader.js
VIDLA-4615 (Prebid Plugin Console Logs should include player ID for Prebid Plugin) - added player id for loader
> VIDLA-4615-2

- src/AdListManager.js
Fix for VIDLA-4590 (Android- 5.28 embedded pages (multi and single) - click to play button not present, clicking play button in controls does NOT enable audio)
> VIDLA-4590

- package.json
- src/AdListManager.js
- src/BcPrebidVast.js
- src/VastRenderer.js
Fix for VIDLA-4623 (iOS 12/iPAD - Displaying black frame and getting VAST Ad Error with out user interaction)
> VIDLA-4623

- package.json
- src/AdListManager.js
- src/BcPrebidVast.js
- src/VastManager.js
VIDLA-4665 (prepare hot fix to address TypeError: m.playlist.currentIndex is not a function error). Added additional validation for player play-listing support (support for playlist.currentIndex function).
> VIDLA-4665

- package.json
- src/AdListManager.js
- src/BcPrebidVast.js
- src/VastManager.js
> VIDLA Version 0.4.11

- package.json
- src/BcPrebidVast.js
- src/DfpUrlGenerator.js
- src/PrebidCommunicator.js
- tests/e2e/auto/DfpUrlGeneratorTest.js
VIDLA-4657 (Add support to call DFP in the case where prebid.js fails to load)
> VIDLA-4657

- tests/e2e/testPages/prebid-body-multi-players.html
Fix for VIDLA-4692 (MAC Chrome - multi-player page (non-embedded) - several VIDEO JS type errors are thrown). Fix done on test page.
> VIDLA-4692

- src/AdListManager.js
Fix for VIDLA-4597 (iOS10/iPad - In-consistent Auto play behavior on Prebid with Options Embedded in Studio test page)
> VIDLA-4597

- src/AdListManager.js
- src/MarkersHandler.js
Fix for VIDLA-4383 (Android, multiple Ad playlist- 2nd content video scrubs to the end or is skipped altogether)
> VIDLA-4383

- package.json
- src/BcPrebidLoader.js
- src/BcPrebidVast.js
- tests/e2e/auto/BcPrebidLoaderTest.js
- tests/e2e/auto/BcPrebidVastTest.js
VSSPP-296 (Implement code to identify which renderer to use)
VSSPP-297 (Implement support for publisher option to override default renderer selection)
> VSSPP-296-297

- src/AdListManager.js
- src/BcPrebidVast.js
- src/ImaVastRenderer.js
- tests/e2e/auto/AdListManagerTest.js
- tests/e2e/auto/BcPrebidVastTest.js
VSSPP-299 (ad code to dynamically load the IMA plugin).
The module ImaVastrenderer.js is placeholder for now and not required code review.
> VSSPP-299 (ad code to dynamically load the IMA plugin)

- src/ImaVastRenderer.js
- tests/e2e/auto/0_Init_Test_Page.js
- tests/e2e/auto/AdListManagerTest.js
- tests/e2e/auto/BcPrebidVastTest.js
- tests/e2e/auto/ImaVastRendererTest.js
- tests/e2e/auto/VastManagerTest.js
- tests/e2e/auto/VastRendererTest.js
VSSPP-300 (Fixed unit tests and added new unit tests for IMA renderer module)
> VSSPP-300-2

- src/BcPrebidVast.js
Support IMA renderer for BC Player 5.28.1 and load IMA plugin script only once in document
> VSSPP-IMA-FOR-BC-5-28

- package.json
- src/BcPrebidVast.js
Fix for VSSPP-717 (Audio from content video is heard when roadblock is not activated)
> Fix for VSSPP-717

- src/ImaVastRenderer.js
Fix for VSSPP-723 (Player controls don't work properly after Stop Ad is issued)
> Fix for VSSPP-723

- package.json
- src/AdapterManager.js
- src/BcPrebidVast.js
Fix for VSSPP-758 (if Multi Ad is used, roadblock adapter functionality does not work)
> Fix for VSSPP-758

- package.json
- src/BcPrebidVast.js
VSSPP-1050 (prebid.js is loaded twice if the plugin is embedded in the Studio but the options are passed in on the page)
> Fix for VSSPP-1050

- src/AdListManager.js
- src/BcPrebidVast.js
- src/ImaVastRenderer.js
Fix for VSSPP-1051 (user has selected click-to-play the renderer uses autoplay) and VSSPP-1052 (user is reporting a black screen on this test page instead of seeing an ad)
Those changes were made to address issue https://github.com/prebid/prebid-js-plugin-brightcove/issues/139
> Fix for VSSPP-1051 and VSSPP-1052

- src/AdListManager.js
- src/VastRenderer.js
Fix for VSSPP-511 (When using MOL, black screen is seen instead of second preroll)
> Fix for VSSPP-511

- package.json
- src/AdListManager.js
- src/BcPrebidVast.js
Fix for VSSPP-1103 (Uncaught type error in playlist page)
> Fix for VSSPP-1103

- src/BcPrebidVast.js
- src/ImaVastRenderer.js
- src/VastRenderer.js
Fix for VSSPP-1111 (click to play button shows for auto-play muted player)
> Fix for VSSPP-1111

- package.json
- src/BcPrebidVast.js
- src/ImaVastRenderer.js
- src/VastRenderer.js
Fix for VSSPP-1052 (user is reporting a black screen on this test page instead of seeing an ad)
> Fix for VSSPP-1052

- src/AdListManager.js
- src/ImaVastRenderer.js
Fix for VSSPP-1115 (IOS - auto-play pages require click (no auto-play functionality))
> Fix for VSSPP-1115
